import img2 from "../assets/mercedes-offer.png";
import img3 from "../assets/nissan-offer.png";
import img4 from "../assets/toyota-offer-2.png";

// export const images = [Img1, Img2, Img3, Img4, Img5, Img6, Img7, Img8];
export const cars = [
  {
    id: 1,
    name: "Mercedes C-Class",
    brand: "Mercedes",
    rating: 4.5,
    features: ["Automatic", "Diesel", "100km/H", "Black"],
    price: 500,
    image: img4,
  },
  {
    id: 2,
    name: "Nissan Maxima",
    brand: "Nissan",
    rating: 4.8,
    features: ["Manual", "Petrol", "100km/H", "Black"],
    price: 1000,
    image: img2,
  },
  {
    id: 3,
    name: "Toyota Camry",
    brand: "Toyota",
    rating: 4.6,
    features: ["Automatic", "Petrol", "200km/H", "Red"],
    price: 200,
    image: img3,
  },
];

// const cars = [
//   {
//     id: 1,
//     img: img2,
//     brand: "toyota",
//     carName: "Bugatti v47",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "diesel",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC500/day",
//   },
//   {
//     id: 2,
//     img: img3,
//     carName: "Chervolette",
//     brand: "audi",
//     ratings: "5 stars",
//     mechanic: "manual",
//     fuel: "petrol",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC1000/day",
//   },
//   {
//     id: 3,
//     img: img4,
//     carName: "Toyota",
//     brand: "honda",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "petrol",
//     speed: "300km/h",
//     color: "red",
//     cost: "GHC200/day",
//   },
//   {
//     id: 4,
//     img: Img,
//     carName: "Bugatti",
//     brand: "nissan",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "petrol",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC200/day",
//   },
//   {
//     id: 5,
//     img: Img,
//     carName: "Bugatti",
//     brand: "nissan",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "petrol",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC200/day",
//   },
//   {
//     id: 6,
//     img: Img,
//     carName: "Bugatti",
//     brand: "nissan",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "petrol",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC200/day",
//   },
//   {
//     id: 7,
//     img: Img,
//     carName: "Bugatti",
//     brand: "mazda",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "petrol",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC200/day",
//   },
//   {
//     id: 8,
//     img: Img,
//     carName: "Bugatti",
//     brand: "honda",
//     ratings: "5 stars",
//     mechanic: "automatic",
//     fuel: "petrol",
//     speed: "100km/h",
//     color: "black",
//     cost: "GHC200/day",
//   },
// ];
